# Inspiration:
# https://github.com/blsmit5728/flexget_files/blob/master/config.yml
# https://github.com/tarzasai/.flexget/blob/master/config.yml

secrets: secrets.yml

templates:
  global:
#    domain_delay:
      # RSS
#      bt-chat.com: 1 seconds
#      ezrss.it: 1 seconds
#      showrss.info: 1 seconds
#      torlock.eu: 1 seconds
#      torrenticity.com: 1 seconds
#      torrentz.me: 1 seconds
#      kickasstorrents.eu: 1 seconds

      # Discover
#      kat.ch: 5 seconds
#      torrentz.eu: 5 seconds
#      rarbg.to: 5 seconds


    regexp:
      reject:
        - (s|d)ub(s|bed)?\b: {from: title}
        - (duo|tri|quadri|tetra|penta|hexa|hepta|octa|ennea|deca)logy 
#        - \b3-?D\b: {from: title}
        - \bR5\b: {from: title}
        - \bWEBSCR\b: {from: title}
        - \bscreener\b: {from: title}
        - \bTS\b: {from: title}
        - \bCam\b: {from: title}
        - "{C_P}": {from: title}
        - \bFRENCH\b: {from: title}
        - \bSPANiSH\b: {from: title}
        - \btrailer\b: {from: title}
        - \bSCR\b: {from: title}
        - TrTd TeaM: {from: title}
        - \[TNTVillage\]: {from: title}
        - \[facepalm\]: {from: title}
        - \bHEVC\b: {from: title}
    content_filter:
      require:
        - '*.avi'
        - '*.mkv'
        - '*.m4v'
        - '*.mp4'
      reject:
        - '*.m2ts'
        - 'password.txt'
        - '*.wmv'
    retry_failed:
      retry_time: 1 hour
      retry_time_multiplier: 2
      max_retries: 5

  Series-Global:
    exists_series:
      - '{{ secrets.path.targetSeries }}'
      - '{{ secrets.path.downloadSeries }}'
    content_size:
      max: 1700
      min: 50 

    # Some titles need little corrections to find matches on metainfo sites.
    manipulate:
      - title:
          replace:
            regexp: '^\[[^\]]*\][^a-z0-9]*'
            format: ''
      - title:
          replace:
            regexp: '^{[^\]]*}[^a-z0-9]*'
            format: ''
      - title:
          replace:
            regexp: '^\([^\]]*\)[^a-z0-9]*'
            format: ''
      # Original title backup
      - tvinfo_title:
          from: title
      # Now the modifications
      - title:
          replace:
            regexp: '.*(marvel|marvels|marvel.s)?.agents.of.(s.h.i.e.l.d.|shield)[\b-.]*'
            format: 'marvels_agents_of_shield.'
      - title:
          replace:
            regexp: '^[^a-z0-9]*heartland.(ca|\(ca\))?[^a-z0-9]*'
            format: 'Heartland.(CA).'

    transmission:
      host: localhost
      port: 9091
      username: '{{ secrets.transmission.username }}'
      password: '{{ secrets.transmission.password }}'
      addpaused: no 
      #magnetization_timeout: 30
      #main_file_only: yes
      #include_subs: yes
      #skip_files:
      #  - '*.[sS]ample'
    thetvdb_lookup: yes
    set:
      content_filename: "{{ tvdb_series_name|default(series_name)|replace('/', '_')|replace(':', ' -')|replace(',', '') }} - {{ series_id }}{% if tvdb_ep_name|default(False) %} - {{ tvdb_ep_name|replace('/', '_')|replace(':', ' -')|replace(',', '') }}{% endif %} - {{ quality }}"
      path: '{{ secrets.path.downloadSeries }}/{{series_name}}'
    pushbullet:
      apikey: '{{ secrets.pushbullet.APIkey }}'
      title: "[FlexGet] {{ series_name }}"
      body: "{{task}} - {{ series_id }}\nFile: {{title}}"

  Series-Feeds:
    inputs:
      - rss: { url: 'https://iptorrents.com/torrents/rss?u=1486500;tp=965b9a84064bb3f6585156350318d4c1;78;79;5;download;s1=0.5;new', silent: yes }

  Series-Discover:
    discover:
      what:
        - emit_series: yes
      from:
        - iptorrents: 
            rss_key: '{{ secrets.iptorrents.rss_key }}'
            uid: 1486500 
            password: '{{ secrets.iptorrents.password }}'
            category: 
              - TV-480p 
              - TV-SD-x264
              - TV-Web-DL
              - TV-x264  
              - TV-MP4

  Movies-Global:
    exists_movie:
      - '{{ secrets.path.targetMovies }}'
      - '{{ secrets.path.downloadMovies }}'
    content_size:
      max: 20000 
      min: 750
    imdb_lookup: yes
    transmission:
      host: localhost
      port: 9091
      username: '{{ secrets.transmission.username }}'
      password: '{{ secrets.transmission.password }}'
      addpaused: yes 
#      magnetization_timeout: 30
#      main_file_only: yes
#      include_subs: yes
#      skip_files:
#        - '*.[sS]ample'
    set:
      path: '{{ secrets.path.downloadMovies }}'
    pushbullet:
      apikey: '{{ secrets.pushbullet.APIkey }}'
      title: "[FlexGet] {{ imdb_name }} {{ imdb_year }}"
      body: "{{task}}\nFile: {{title}}"
      url: "imdb:///title/{{ imdb_id }}?src=mdot"

  Movies-Discover:
    discover:
      what:
        - movie_list: trakt movies
      from:
        - iptorrents: 
            rss_key: '{{ secrets.iptorrents.rss_key }}' 
            uid: 1486500 
            password: '{{ secrets.iptorrents.password }}'
            category: 
              - Movie-HD-Bluray
              - Movie-MP4
              - Movie-BD-Rip
              - Movie-3D 

  Movies-Queued:
    #movie_queue: accept
    template: Movies-Discover
    disable:
      - seen_movies
      - seen
    list_remove:
      - trakt_list:
          username: '{{ secrets.trakt.username }}'
          list: Movie Queue
          type: movies
    list_add:
      - trakt_list:
          username: '{{ secrets.trakt.username }}'
          list: watchlist
          type: movies

#  Sub-Move:
#    move:
#      along:
#        - srt
#        - en.srt
#        - eng.srt

tasks:
  Series-GetFollowing:
    priority: 5
    template:
      - Series-Global
      - Series-Discover
#      - Series-Feeds
    configure_series:
      from:
        trakt_list:
          username: '{{ secrets.trakt.username }}'
          account: '{{ secrets.trakt.account }}'
          list: 'TV Following'
          type: shows
      settings:
        target: 480p h264
        timeframe: 8 hours
        quality: 480p-1080p !h265
        propers: 12 hours
#    series:
#      - "Marvel's Agents of S.H.I.E.L.D.":
#          alternate_name:
#            -  "Marvels Agents of S.H.I.E.L.D."
#            -  "Marvel's Agents of SHIELD"
#            -  "Marvels Agents of SHIELD"
#      - "Once Upon a Time":
#          exact: yes
#          alternate_name:
#            - "Once Upon a Time (2011)"
#            - "Once Upon a Time 2011"

  Series-GetInteresting:
    priority: 6
    template:
      - Series-Global
      - Series-Discover
    configure_series:
      from:
        trakt_list:
          username: '{{ secrets.trakt.username }}'
          account: '{{ secrets.trakt.account }}'
          list: 'TV Interesting'
          type: shows
      settings:
        target: 720p h264
        timeframe: 5 hours
        quality: 480p-1080p !h265
        propers: 12 hours

#  ClearTransmission:
#    priority: 7
#    no_entries_ok: yes
#    clean_transmission:
#      username: '{{ secrets.transmission.username }}'
#      password: '{{ secrets.transmission.password }}'
#      enabled: yes
#    disable: [details]

#  Sort-Series:
#    priority: 8
#    template:
#      - Sub-Move
#    filesystem: 
#      path: '{{ secrets.path.downloadSeries }}/'
#      regexp: '.*\.(avi|mkv|mp4)$'
#      recursive: yes
#    disable: seen
#    thetvdb_lookup: yes
#    metainfo_series: yes
#    require_field:
#      - series_season
#      - series_episode
#    accept_all: yes
#    regexp:
#      reject:
#        - sample
#    move:
#      to: "/mnt/nas/Video/Serier/{{ tvdb_series_name|default(series_name)|replace('/', '_')|replace(':', ' ') }}/{% if series_id_type == 'ep' %}Season {{ tvdb_season|default(series_season)|pad(2) }}/{% endif %}"
#      clean_source: 50
#    pushbullet:
#      apikey: '{{ secrets.pushbullet.APIkey }}'
#      title: "[FlexGet] {{ series_name }}"
#      body: "{{task}} - {{ series_id }}\nFile: {{title}}"

  Series-SetBegin:
    priority: 9
    configure_series:
      from:
        trakt_list:
          username: '{{ secrets.trakt.username }}'
          account: '{{ secrets.trakt.account }}'
          list: 'TV Begin'
          type: shows
      settings:
        begin: S01E01
    trakt_list:
      username: '{{ secrets.trakt.username }}'
      account: '{{ secrets.trakt.account }}'
      list: 'TV Begin'
      type: shows
    accept_all: yes
    list_add:
      - trakt_list:
          username: '{{ secrets.trakt.username }}'
          list: 'TV Following'
          type: movies
    list_remove:
      - trakt_list:
          username: '{{ secrets.trakt.username }}'
          list: 'TV Begin'
          type: movies
    pushbullet:
      apikey: '{{ secrets.pushbullet.APIkey }}'
      title: "[FlexGet] {{ series_name }}"
      body: "{{task}}"


  Movies-SetQueue:
    priority: 10
    template: no_global
    trakt_list:
      username: '{{ secrets.trakt.username }}'
      account: '{{ secrets.trakt.account }}'
      list: Movie Queue
      type: movies
    accept_all: yes
    list_add:
      - movie_list: trakt movies

  Movies-Get3D:
    priority: 12
    template: 
      - Movies-Global
      - Movies-Queued
    torrent_alive:
      min_seeds: 5
    quality: 720p+  h264 !mp3 !aac
    regexp:
      accept:
        - (3D|3d)
  
  Movies-Get1080p:
    priority: 13
    template: 
      - Movies-Global
      - Movies-Queued
    torrent_alive:
      min_seeds: 5
    quality: 1080p  h264 !mp3 !aac

  Movies-Get720p:
    priority: 14
    template: 
      - Movies-Global
      - Movies-Queued
    torrent_alive:
      min_seeds: 5
    quality: 720p  h264 !mp3 !aac

  Movies-Get:
    priority: 15
    template: 
      - Movies-Global
      - Movies-Queued
    torrent_alive:
      min_seeds: 2
    quality: 480p-720p !h265  !sdtv !dvdscr !bdscr
    delay: 7 days

#  Sort-Movies:
#    priority: 16
#    template:
#      - Sub-Move
#    filesystem: 
#      path: '{{ secrets.path.downloadMovies }}/'
#      regexp: '.*\.(avi|mkv|mp4)$'
#      recursive: yes
#    disable: seen
#    tmdb_lookup: yes
#    imdb_lookup: yes
#    accept_all: yes
#    regexp:
#      reject:
#        - sample
#    move:
#      to: '/mnt/nas/Video/Film/{{ tmdb_name|replace("/", "_")|replace(":", " ") }} ({{ tmdb_year }})'
#      clean_source: 50
#    pushbullet:
#      apikey: '{{ secrets.pushbullet.APIkey }}'
#      title: "[FlexGet] {{ imdb_name }} {{ imdb_year }}"
#      body: "{{task}}\nFile: {{title}}"
#      url: "imdb:///title/{{ imdb_id }}?src=mdot"



schedules:
#  - tasks: [ClearTransmission, Sort-*]
#    schedule:
#      hour: 0-9
#      minute: "*/60"
  - tasks: Series-Get* 
    schedule:
      minute: "*/5"
  - tasks: Series-SetBegin
    schedule:
      minute: "*/720"
  - tasks: Movies-*
    schedule:
      minute: "*/30"


web_server:
  bind: 0.0.0.0
  port: 5050
api: yes
webui: yes

